env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

builds:
  -
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64

archives:
  -
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
