# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GoReleaser Action'
description: 'GitHub Action for GoReleaser, a release automation tool for Go projects'
author: 'goreleaser'
branding:
  color: 'green'
  icon: 'package'

inputs:
  distribution:
    description: 'GoReleaser Distribution (goreleaser or goreleaser-pro)'
    default: 'goreleaser'
    required: false
  version:
    description: 'GoReleaser version'
    default: 'latest'
    required: false
  args:
    description: 'Arguments to pass to GoReleaser'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    default: '.'
    required: false
  install-only:
    description: 'Just install GoReleaser'
    default: 'false'
    required: false
  github-token:
    description: >
       Used to verifiy the Git tag exists on docker/buildx repo. Since there's a
       default, this is typically not supplied by the user. When running this
       action on github.com, the default value is sufficient. When running on
       GHES, you can pass a personal access token for github.com if you are
       experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
    required: false

outputs:
  artifacts:
    description: 'Build result artifacts'
  metadata:
    description: 'Build result metadata'

runs:
  using: 'node16'
  main: 'dist/index.js'
