name: test

on:
  pull_request:
    branches:
      - master
      - feature/*
      - releases/*
  push:
    branches:
      - master
      - feature/*
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Install
        run: npm install
      -
        name: Test
        run: npm run test
